# --- Stage 1: Build frontend with Node.js ---
FROM node:18 AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest and build
COPY . .
RUN npm run build


# --- Stage 2: Serve with Nginx as non-root user ---
FROM nginx:alpine

# Clean default nginx html content
RUN rm -rf /usr/share/nginx/html/*

# Copy built app from builder
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf


# Create non-root user for OpenShift compatibility
RUN addgroup -S nginxuser && adduser -S nginxuser -G nginxuser

# OpenShift file permission requirements
RUN chmod -R 777 /var/cache/nginx \
 && chown -R nginxuser:nginxuser /var/cache/nginx \
 && chown -R nginxuser:nginxuser /var/log/nginx \
 && chown -R nginxuser:nginxuser /etc/nginx

# Handle nginx.pid file permissions
RUN touch /var/run/nginx.pid \
 && chown -R nginxuser:nginxuser /var/run/nginx.pid \
 && chmod 777 /var/run/nginx.pidp

# Expose app port
EXPOSE 8080

# Use non-root user
USER nginxuser

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]