
FROM docker.io/library/node:18 AS builder
WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .
RUN npm run build



FROM docker.io/library/nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf


RUN chgrp -R 0 /var/cache/nginx /var/run /var/log/nginx /etc/nginx /usr/share/nginx/html \
 && chmod -R g+rwX /var/cache/nginx /var/run /var/log/nginx /etc/nginx /usr/share/nginx/html \
 && touch /var/run/nginx.pid \
 && chgrp 0 /var/run/nginx.pid && chmod g+rw /var/run/nginx.pid

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
